CREATE DATABASE IF NOT EXISTS energy_tariff;
USE energy_tariff;

CREATE TABLE IF NOT EXISTS fact_tariff_search_simple (
    id INT AUTO_INCREMENT PRIMARY KEY,
    current_supplier_name VARCHAR(100) NOT NULL,
    pay_method VARCHAR(100) NOT NULL,
    EV_question VARCHAR(100) NOT NULL,
    new_supplier_name VARCHAR(100) NOT NULL,
    tariff_name VARCHAR(150) NOT NULL,
    tariff_type VARCHAR(50) NOT NULL,
    fixed_price_length_months INT,
    is_green BOOLEAN DEFAULT FALSE,
    region_code VARCHAR(10),
    region_name VARCHAR(100),
    dno_name VARCHAR(100),
    dno_id VARCHAR(20),
    postcode VARCHAR(10),
    outward_code VARCHAR(4),
    latitude DECIMAL(10, 8),
    longitude DECIMAL(11, 8),
    fuel_type VARCHAR(20) NOT NULL,
    search_date DATE NOT NULL,
    month INT,
    year INT,
    annual_electricity_kwh INT,
    annual_gas_kwh INT,
    unit_rate DECIMAL(10, 4),
    standing_charge DECIMAL(10, 4),
    exit_fee DECIMAL(10, 2) DEFAULT 0.00,
    annual_cost_current DECIMAL(10, 2),
    annual_cost_new DECIMAL(10, 2),
    valid_from DATE,
    valid_to DATE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_postcode (postcode),
    INDEX idx_region (region_code),
    INDEX idx_supplier (new_supplier_name),
    INDEX idx_tariff (tariff_name),
    INDEX idx_fuel_type (fuel_type),
    INDEX idx_search_date (search_date),
    INDEX idx_valid_dates (valid_from, valid_to)
);

